server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/union-wp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update



